language: node_js

node_js:
  - 8
  - 7
  - 6
  - 5

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm run test
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  local_dir: 'build'
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  slack: ninjaro:clZjvDamAByBYA004CYcYlH6
  email:
    - theodoro.pelingan@gmail.com
