language: node_js

node_js:
  - 8

script:
  - npm run test
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --user codecov

after_success:
  - codecov --file coverage/lcov.info --disable search

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  local_dir: 'build'
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop

notifications:
  slack: ninjaro:$SLACK_TOKEN
  email:
    - theodoro.pelingan@gmail.com
